### ISSUE TITLE
Design a Navbar component

### ISSUE THREAD

**Issue by i-am-SnehaChauhan** [i-am-SnehaChauhan/book_lab#5]
**Description:**

**Objective:**
Design a responsive and visually appealing Navbar component for a website. The Navbar should include the following elements:

1. **Home:** Link to the homepage of the website.
2. **Contact Us:** Link to the contact us page.
3. **Add Book:** Link or button for adding a book.
4. **Favourite:** Link or button to view and manage favorite items.
5. **Login:** Button to initiate the login process.

**Requirements:**
- The Navbar should be easily navigable.
- Ensure the design is responsive for various screen sizes.
- Consider using appropriate icons for each navigation item.
- The "Login" button should be distinct and easily noticeable.

**Additional Information:**
Feel free to use any modern design principles, and consider the overall theme of the website. If you have any questions or need clarification, please don't hesitate to ask.

**Comment by aindree-2005** [comment]
@i-am-SnehaChauhan can I work on this? I am planning to use Tailwind and GSAP for sleek design and animated navbar

**Comment by Touseef-md** [comment]
Hey, I @i-am-SnehaChauhan would like to work on this.

**Comment by i-am-SnehaChauhan** [comment]
@aindree-2005 please complete this in 3 days else i have to assign it to @Touseef-md

**Comment by SAQLAINAP** [comment]
Hey @i-am-SnehaChauhan , i would like to get my hands on this beautiful opportunity. I would most likely use simple and concise bootstrap or tailwind with responsiveness support.
